### ISSUE TITLE
aws_elasticache_replication_group  supports auto_minor_version_upgrade parameter

### ISSUE THREAD

**Issue by 3h4x** [cloudposse/terraform-aws-elasticache-redis#117]
## Describe the Feature

`auto_minor_version_upgrade` - (Optional) Specifies whether a minor engine upgrades will be applied automatically to the underlying Cache Cluster instances during the maintenance window. Defaults to true.

https://registry.terraform.io/providers/hcavarsan/aws/latest/docs/resources/elasticache_replication_group#auto_minor_version_upgrade

## Use Case

It's defaults to `true` which might be not desired under some circumstances.

**Comment by Nuru** [comment]
While `aws_elasticache_replication_group` accepts an `auto_minor_version_upgrade` input, it actually [is ignored](https://github.com/hashicorp/terraform-provider-aws/pull/16756) and does nothing.
