### ISSUE TITLE
0.40.0 Missing arguments to pass existing security groups

### ISSUE THREAD

**Issue by z0rc** [cloudposse/terraform-aws-elasticache-redis#123]
https://github.com/cloudposse/terraform-aws-elasticache-redis/pull/119 completely removed option to pass existing security groups to cluster, it just allows to create a new SG. Please revert this decision.

**Comment by nitrocode** [comment]
Please see comment https://github.com/cloudposse/terraform-aws-elasticache-redis/pull/119#issuecomment-866229500

**Comment by z0rc** [comment]
Okay, it's called `security_groups` now. Why this kind of change happened in minor release is unexciting.

**Comment by nitrocode** [comment]
@z0rc This is all part of standardizing usage of the security group module across all of the cloudposse modules. We had similar growing pains with bringing `context.tf`. We'll work on our upgrade process more going forward. If you have suggestions, please let us know in our slack community.

If other issues come up, please file a new ticket.

**Comment by Nuru** [comment]
@z0rc We are taking feedback like yours into account and have marked v0.40.0 pre-release. We recommend using 0.39.0 for now and waiting for a later release which will provide better backward compatibility and clearer migration instructions.
