### ISSUE TITLE
Argument is deprecated [elasticache_replication_group]

### ISSUE THREAD

**Issue by adamwshero** [cloudposse/terraform-aws-elasticache-redis#155]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
When planning an elasticache redis instance with a cluster_size = 2 and cluster_mode_enabled = false, using v0.42.0, a deprecation warning is issued.

## Expected Behavior
No deprecation warnings are issued and a you have a clean plan.

## Steps to Reproduce
1. Create a redis instance with a cluster size of 2 and cluster mode disabled.
2. Run 'terraform plan'
3. See error 
```
│ Warning: Argument is deprecated
│ 
│   with aws_elasticache_replication_group.default,
│   on main.tf line 116, in resource "aws_elasticache_replication_group" "default":
│  116: resource "aws_elasticache_replication_group" "default" {
│ 
│ Use num_node_groups and replicas_per_node_group instead
│ 
│ (and 4 more similar warnings elsewhere)
```

## Screenshots
N/A

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: OSx
 - Version 12.1

## Additional Context
N/A

**Comment by Epic55** [comment]
I have the same issue, but cluster size = 1.

**Comment by purplepangolin** [comment]
I get the same issue following a recent upgrade of aws provider version. Current settings:
Terraform v1.1.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.12.0

Previously I was usin
terraform v1.0.1
provider registry.terraform.io/hashicorp/aws v3.75.1
