### ISSUE TITLE
Use preferred_cache_cluster_azs for availability zones

### ISSUE THREAD

**Issue by odie5533** [cloudposse/terraform-aws-elasticache-redis#173]
## Describe the Feature

The module should use [preferred_cache_cluster_azs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#preferred_cache_cluster_azs) in the aws_elasticache_replication_group. This would allow us to specify the preferred primary node. Also the parameter used for AZs, availability_zones, is deprecated.

> [availability_zones](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#availability_zones) - (Optional, **Deprecated** use preferred_cache_cluster_azs instead) List of EC2 availability zones in which the replication group's cache clusters will be created. The order of the availability zones in the list is not considered.

> [preferred_cache_cluster_azs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#preferred_cache_cluster_azs) - (Optional) List of EC2 availability zones in which the replication group's cache clusters will be created. The order of the availability zones in the list is considered. The first item in the list will be the primary node. Ignored when updating.

## Alternatives Considered

It may be possible to modify the resource inside the module. I have not looked into this workaround.

**Comment by milldr** [comment]
resolved with #198
