### ISSUE TITLE
zone_id input listed as not required, throws error if not defined

### ISSUE THREAD

**Issue by kuritonasu** [cloudposse/terraform-aws-elasticache-redis#19]
I might be missing something here, but the 'zone_id' input is listed as not required with a default value of 'false' thus if it's not defined, TF throws an error:

> Error: Error applying plan:
> 
> 1 error(s) occurred:
> 
> * module.elasticache.module.elasticache-redis.module.dns.aws_route53_record.default: 1 error(s) occurred:
> 
> * aws_route53_record.default: NoSuchHostedZone: No hosted zone found with ID: false
> 	status code: 404, request id: a98d55b6-a9ca-11e8-87cd-a1203e2fe555

If it is set to empty literals:

> Error: module.elasticache.module.elasticache-redis.module.dns.aws_route53_record.default: zone_id must not be empty

**Comment by MoonMoon1919** [comment]
I noticed this as well, I can make a fix within the next few days, hopefully this weekend.

**Comment by MoonMoon1919** [comment]
Fixed in https://github.com/cloudposse/terraform-aws-elasticache-redis/releases/tag/0.7.2
