### ISSUE TITLE
An argument named "availability_zones" is not expected here.

### ISSUE THREAD

**Issue by muhammadasgharaliqureshi** [cloudposse/terraform-aws-elasticache-redis#199]
### Describe the Bug

In module code at [line 25](https://github.com/cloudposse/terraform-aws-elasticache-redis/blob/main/main.tf#L125) we have

```terraform  
availability_zones         = length(var.availability_zones) == 0 ? null : [for n in range(0, var.cluster_size) : element(var.availability_zones, n)]
```
for terraform resource `aws_elasticache_replication_group` but this argument is no more available for terraform resource aws_elasticcache_replication_group [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group)

![image](https://github.com/cloudposse/terraform-aws-elasticache-redis/assets/64986244/6bbf3f02-168d-4528-9317-5e74d14d9907)

### Expected Behavior

Terraform validate and terraform apply should work on module example

### Steps to Reproduce

Just try running following module example
https://github.com/cloudposse/terraform-aws-elasticache-redis/tree/main/examples/complete

- > Terraform init
- > Terraform apply 

### Screenshots

![image](https://github.com/cloudposse/terraform-aws-elasticache-redis/assets/64986244/6bbf3f02-168d-4528-9317-5e74d14d9907)

### Environment

- OS: Kali GNU/Linux
- Version 2023.1
- Module version ~> 0.49
- Terraform version 1.4.6

**Comment by mbilal-xgrid** [comment]
+1

**Comment by AbuBakkarBinAkmal** [comment]
+1

**Comment by AliHamzaX** [comment]
+1

**Comment by muhammadasgharaliqureshi** [comment]
Related to https://github.com/cloudposse/terraform-aws-elasticache-redis/issues/173 and https://github.com/cloudposse/terraform-aws-elasticache-redis/issues/197

**Comment by rajatrj16** [comment]
Upgrading the provider won't help
I am still getting 
```
╷
│ Error: Unsupported argument
│ 
│   on .terraform/modules/elasticache_redis.elasticache-redis/main.tf line 125, in resource "aws_elasticache_replication_group" "default":
│  125:   availability_zones         = length(var.availability_zones) == 0 ? null : [for n in range(0, var.cluster_size) : element(var.availability_zones, n)]
│ 
│ An argument named "availability_zones" is not expected here.
╵
```

**I have tried to replace `availability_zones` with `preferred_cache_cluster_azs` as mentioned in the [issue-197](https://github.com/cloudposse/terraform-aws-elasticache-redis/issues/197) but then getting**
```
╷
│ Error: Unsupported argument
│ 
│   on ../../modules/elastic-cache/main.tf line 22, in module "elasticache-redis":
│   22:   preferred_cache_cluster_azs          = var.availability_zones
│ 
│ An argument named "preferred_cache_cluster_azs" is not expected here.
╵
```

**Comment by ervinb** [comment]
If you happen to use Terragrunt, you can overwrite this module's [version-contraint](https://developer.hashicorp.com/terraform/language/expressions/version-constraints#-3), so the `aws` module stays below `5.x`:

```tf
terraform {
  source = "git::https://github.com/cloudposse/terraform-aws-elasticache-redis//.?ref=0.51.0"
}

generate "versions" {
  path = "versions.tf"
  if_exists = "overwrite"

  contents = <<-EOF
  terraform {
    required_version = ">= 0.14.0"

    required_providers {
      aws = {
        source  = "hashicorp/aws"
        version = "~> 4.18"
      }
    }
  }
  EOF
}

locals {...}

inputs = {...}

```

**Comment by milldr** [comment]
#198 should have resolved breaking changes from AWS provider v5. Please update to the latest and retry

**Comment by muhammadasgharaliqureshi** [comment]
Thanks @milldr yes looks good now, closing this issue now.
