### ISSUE TITLE
security_groups input description is slightly misleading

### ISSUE THREAD

**Issue by kuritonasu** [cloudposse/terraform-aws-elasticache-redis#20]
The current description of the security_groups input is "AWS security group ids", which originally made me think that I should provide the module with pre-created security group ids. Since the module generates its own security groups, I believe that a more accurate description would be along the lines of "List of security group IDs to be allowed to connect to the cluster" (in line with your Elasticsearch's module secgroup input description)

Oh and thank you cloudposse people for the quality modules!

**Comment by osterman** [comment]
@kuritonasu thanks for the report. We'll get the documentation fixed.
