### ISSUE TITLE
subnet_group_name is always created

### ISSUE THREAD

**Issue by estein9825** [cloudposse/terraform-aws-elasticache-redis#30]
There are cases where you want to create a new redis instance but attach it to an existing subnet group.  However, this is currently not possible with this implementation.  You should be able to disable creating the subnet group and instead pass it in as a variable.

**Comment by aknysh** [comment]
@estein9825  thank you for testing and submitting the issue.
If you know how to implement it, please submit a PR, we'll review it promptly.
