### ISSUE TITLE
Add auth_token_update_strategy option

### ISSUE THREAD

**Issue by karlismelderis** [cloudposse/terraform-aws-elasticache-redis#55]
Currently, any auth_token changes are destroying and are recreating Redis cluster.

AWS API has option to set new token and chose update strategy: SET or ROTATE

https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_ModifyCacheCluster.html

**Comment by Routhinator** [comment]
This is a pretty key feature, FWIW. Security token cycling is something that should be able to be done frequently and with minimal disruption.... replacing the cluster adds a lot of overhead.

**Comment by Steve-Louie-Bose** [comment]
Looks like it's supported now. https://github.com/hashicorp/terraform-provider-aws/pull/16203
