### ISSUE TITLE
Error evaluating cluster_mode when var.cluster_mode_enabled = true

### ISSUE THREAD

**Issue by rewt** [cloudposse/terraform-aws-elasticache-redis#64]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Module fails to create `Clustered Redis` elasticache resource with error:
```
module.subnets.aws_nat_gateway.default[1]: Still creating... [1m50s elapsed]
module.subnets.aws_nat_gateway.default[0]: Still creating... [1m50s elapsed]
module.subnets.aws_nat_gateway.default[0]: Creation complete after 1m57s [id=]
module.subnets.aws_nat_gateway.default[1]: Creation complete after 1m57s [id=]
module.subnets.aws_route.default[1]: Creating...
module.subnets.aws_route.default[0]: Creating...
module.subnets.aws_route.default[0]: Creation complete after 1s [id=]
module.subnets.aws_route.default[1]: Creation complete after 1s [id=]

Error: Either `number_cache_clusters` or `cluster_mode` must be set

  on ../../main.tf line 81, in resource "aws_elasticache_replication_group" "default":
  81: resource "aws_elasticache_replication_group" "default" {
```

## Expected Behavior
Successful creation of `Clustered Redis` resource when `var.cluster_mode_enabled=true`

## Steps to Reproduce
1.  Clone repo
2. Update `cluster_mode_enabled` `default=true`
3. Update `cluster_mode_replicas_per_node_group` `default=1`
4. Update `cluster_mode_num_node_groups` `default=3`

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):
```
Mac OS
Terraform v0.12.23
+ provider.aws v2.53.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```

## Additional Context
[plan.txt](https://github.com/cloudposse/terraform-aws-elasticache-redis/files/4350853/plan.txt)

**Comment by rewt** [comment]
`number_cache_clusters` is not compatible with `cluster_mode` so having condition evaluate between the two will always error.

https://github.com/terraform-providers/terraform-provider-aws/issues/10458#issuecomment-549522250

**Comment by rewt** [comment]
https://github.com/cloudposse/terraform-aws-elasticache-redis/blob/9904a81caa17bbf6abf7e3b82fdfa0ac7aa1215a/main.tf#L88

The issue is that `aws_elasticache_replication_group` cannot have both `cluster_mode` and `number_cache_clusters` as specified [here](https://github.com/terraform-providers/terraform-provider-aws/issues/10458).

**Comment by Gowiem** [comment]
@rewt I'm seeing the same. Did you get that figured out?

**Comment by rewt** [comment]
> @rewt I'm seeing the same. Did you get that figured out?

I just used my own code for the time being.

**Comment by Gowiem** [comment]
Gotcha.

For others that come across this issue, this seems to be a recent change in AWS APIs or the underlying AWS Provider which causes this problem. [I attempted to fix this in my own fork here](https://github.com/cloudposse/terraform-aws-elasticache-redis/compare/master...masterpointio:fix-cluster-mode), but I wasn't able to get that to work so I instead swapped over to not using `cluster_mode_enabled` and increasing my `cluster_size` which provides enough resilience for my current project.

**Comment by samsullivan** [comment]
@Gowiem I took a crack at it and it's working for me: https://github.com/cloudposse/terraform-aws-elasticache-redis/pull/65. Using `null` instead of `0` removed the need for setting `depends_on`.

Also, it looked like we also needed to get rid of `availability_zones` (maybe it's worth the extra work to implement `preferred_availability_zones`?).

**Comment by Gowiem** [comment]
@samsullivan Aha `null` > `0` did it. Interesting. Thanks for pointing that out and fixing via PR. Hopefully that helps out others if they require a cluster!

I would assume `preferred_availability_zones` would be desirable since you would want your redis servers co-located in the same AZs as your application servers. Probably worth opening another bug for that enhancement.
