### ISSUE TITLE
Missing arguments

### ISSUE THREAD

**Issue by ac-hibbert** [cloudposse/terraform-aws-elasticache-redis#70]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug

I've been looking through the arguments in the page https://www.terraform.io/docs/providers/aws/r/elasticache_replication_group.html. This module seems to be missing the following:

auto_minor_version_upgrade
kms_key_id
security_group_names
snapshot_arns
snapshot_name

## Expected Behavior

These arguments exist and are configurable

**Comment by Nuru** [comment]
Closing as a combination of "fixed" and "wontfix":
- `auto_minor_version_upgrade` actually [does nothing](https://github.com/hashicorp/terraform-provider-aws/pull/16756). We will wait until it is effective before adding it.
- `kms_key_id` added in #75 
- `snapshot_arns` added in #97 
- `snapshot_name` added in #102 
- `security_group_names` appears to be obsolescent (on its way to not being supported). We will wait for someone to provide a current use case for it.
