### ISSUE TITLE
Issue managing 6.x clusters

### ISSUE THREAD

**Issue by andrewward** [cloudposse/terraform-aws-elasticache-redis#88]
When creating a cluster you have to specify 6.x as the `engine_version` otherwise you get this error:

```
Error creating Elasticache Replication Group: InvalidParameterValue: Specific version selection is not allowed for '6.0.5', please use '6.x'
```

After creating the cluster using `6.x` subsiquent runs fail with the following error until you update `engine_version` to `6.0.5`:

```
error updating Elasticache Replication Group (harbor-cache): InvalidParameterCombination: Upgrading minor engine version for redis '6.x' using modify API is not allowed, please use Service Updates
```

**Comment by Xyaren** [comment]
Manually setting the engine_version to `6.0.5` **after** creating the cluster with `6.x` will stop including it in consequent plans.
This is probably a workaround with limited lifetime, as any update on the minor/micro version by aws will probably result in plans failing.

**Comment by cocotton** [comment]
Related: https://github.com/hashicorp/terraform-provider-aws/issues/15625

**Comment by jseiser** [comment]
The previous `related` issue was closed, and a new one is in place.

Related: https://github.com/hashicorp/terraform-provider-aws/pull/18920

**Comment by jseiser** [comment]
This should be fixed in the next provider: 3.38.0

https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md

**Comment by guidoilbaldo** [comment]
I've tested the creation of a redis6.x cluster this morning with the latest AWS provider for TF version 3.38.0. It worked like a charm. The issue can be closed.
Thank you!

**Comment by andrewward** [comment]
Thanks for confirming @guidoilbaldo!
